-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity flow_in_compute_out is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_in_V_AWVALID : OUT STD_LOGIC;
    m_axi_in_V_AWREADY : IN STD_LOGIC;
    m_axi_in_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_WVALID : OUT STD_LOGIC;
    m_axi_in_V_WREADY : IN STD_LOGIC;
    m_axi_in_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_in_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_WLAST : OUT STD_LOGIC;
    m_axi_in_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_ARVALID : OUT STD_LOGIC;
    m_axi_in_V_ARREADY : IN STD_LOGIC;
    m_axi_in_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_in_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_in_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_RVALID : IN STD_LOGIC;
    m_axi_in_V_RREADY : OUT STD_LOGIC;
    m_axi_in_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_in_V_RLAST : IN STD_LOGIC;
    m_axi_in_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_BVALID : IN STD_LOGIC;
    m_axi_in_V_BREADY : OUT STD_LOGIC;
    m_axi_in_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_in_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_V_offset : IN STD_LOGIC_VECTOR (57 downto 0);
    m_axi_out_V_AWVALID : OUT STD_LOGIC;
    m_axi_out_V_AWREADY : IN STD_LOGIC;
    m_axi_out_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_out_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_out_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_WVALID : OUT STD_LOGIC;
    m_axi_out_V_WREADY : IN STD_LOGIC;
    m_axi_out_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_out_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_out_V_WLAST : OUT STD_LOGIC;
    m_axi_out_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_ARVALID : OUT STD_LOGIC;
    m_axi_out_V_ARREADY : IN STD_LOGIC;
    m_axi_out_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_out_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_out_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_RVALID : IN STD_LOGIC;
    m_axi_out_V_RREADY : OUT STD_LOGIC;
    m_axi_out_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_out_V_RLAST : IN STD_LOGIC;
    m_axi_out_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_V_BVALID : IN STD_LOGIC;
    m_axi_out_V_BREADY : OUT STD_LOGIC;
    m_axi_out_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    out_V_offset : IN STD_LOGIC_VECTOR (57 downto 0);
    mem_in_address : IN STD_LOGIC_VECTOR (63 downto 0);
    mem_out_address : IN STD_LOGIC_VECTOR (63 downto 0);
    data_len : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of flow_in_compute_out is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_167 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal reg_189 : STD_LOGIC_VECTOR (57 downto 0);
    signal grp_read_input_fu_126_ap_start : STD_LOGIC;
    signal grp_read_input_fu_126_ap_done : STD_LOGIC;
    signal grp_read_input_fu_126_ap_idle : STD_LOGIC;
    signal grp_read_input_fu_126_ap_ready : STD_LOGIC;
    signal grp_read_input_fu_126_m_axi_in_V_AWVALID : STD_LOGIC;
    signal grp_read_input_fu_126_m_axi_in_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_WVALID : STD_LOGIC;
    signal grp_read_input_fu_126_m_axi_in_V_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_WLAST : STD_LOGIC;
    signal grp_read_input_fu_126_m_axi_in_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARVALID : STD_LOGIC;
    signal grp_read_input_fu_126_m_axi_in_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_read_input_fu_126_m_axi_in_V_RREADY : STD_LOGIC;
    signal grp_read_input_fu_126_m_axi_in_V_BREADY : STD_LOGIC;
    signal grp_read_input_fu_126_elemStream_V_V_din : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_read_input_fu_126_elemStream_V_V_write : STD_LOGIC;
    signal grp_write_output_fu_139_ap_start : STD_LOGIC;
    signal grp_write_output_fu_139_ap_done : STD_LOGIC;
    signal grp_write_output_fu_139_ap_idle : STD_LOGIC;
    signal grp_write_output_fu_139_ap_ready : STD_LOGIC;
    signal grp_write_output_fu_139_resultStream_V_V_read : STD_LOGIC;
    signal grp_write_output_fu_139_m_axi_out_V_AWVALID : STD_LOGIC;
    signal grp_write_output_fu_139_m_axi_out_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_WVALID : STD_LOGIC;
    signal grp_write_output_fu_139_m_axi_out_V_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_WLAST : STD_LOGIC;
    signal grp_write_output_fu_139_m_axi_out_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARVALID : STD_LOGIC;
    signal grp_write_output_fu_139_m_axi_out_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_output_fu_139_m_axi_out_V_RREADY : STD_LOGIC;
    signal grp_write_output_fu_139_m_axi_out_V_BREADY : STD_LOGIC;
    signal grp_dummy_compute_fu_153_ap_start : STD_LOGIC;
    signal grp_dummy_compute_fu_153_ap_done : STD_LOGIC;
    signal grp_dummy_compute_fu_153_ap_idle : STD_LOGIC;
    signal grp_dummy_compute_fu_153_ap_ready : STD_LOGIC;
    signal grp_dummy_compute_fu_153_elemStream_V_V_read : STD_LOGIC;
    signal grp_dummy_compute_fu_153_resultStream_V_V_din : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_dummy_compute_fu_153_resultStream_V_V_write : STD_LOGIC;
    signal grp_read_input_fu_126_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal elemStream_V_V_full_n : STD_LOGIC;
    signal elemStream_V_V_write : STD_LOGIC;
    signal grp_write_output_fu_139_ap_start_reg : STD_LOGIC := '0';
    signal resultStream_V_V_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal resultStream_V_V_empty_n : STD_LOGIC;
    signal resultStream_V_V_read : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_dummy_compute_fu_153_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal elemStream_V_V_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal elemStream_V_V_empty_n : STD_LOGIC;
    signal elemStream_V_V_read : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal resultStream_V_V_full_n : STD_LOGIC;
    signal resultStream_V_V_write : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component read_input IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_in_V_AWVALID : OUT STD_LOGIC;
        m_axi_in_V_AWREADY : IN STD_LOGIC;
        m_axi_in_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_WVALID : OUT STD_LOGIC;
        m_axi_in_V_WREADY : IN STD_LOGIC;
        m_axi_in_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_in_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_WLAST : OUT STD_LOGIC;
        m_axi_in_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_ARVALID : OUT STD_LOGIC;
        m_axi_in_V_ARREADY : IN STD_LOGIC;
        m_axi_in_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_RVALID : IN STD_LOGIC;
        m_axi_in_V_RREADY : OUT STD_LOGIC;
        m_axi_in_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_in_V_RLAST : IN STD_LOGIC;
        m_axi_in_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_BVALID : IN STD_LOGIC;
        m_axi_in_V_BREADY : OUT STD_LOGIC;
        m_axi_in_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_V_offset : IN STD_LOGIC_VECTOR (57 downto 0);
        address : IN STD_LOGIC_VECTOR (63 downto 0);
        data_len : IN STD_LOGIC_VECTOR (31 downto 0);
        elemStream_V_V_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        elemStream_V_V_full_n : IN STD_LOGIC;
        elemStream_V_V_write : OUT STD_LOGIC );
    end component;


    component write_output IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        resultStream_V_V_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        resultStream_V_V_empty_n : IN STD_LOGIC;
        resultStream_V_V_read : OUT STD_LOGIC;
        m_axi_out_V_AWVALID : OUT STD_LOGIC;
        m_axi_out_V_AWREADY : IN STD_LOGIC;
        m_axi_out_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_WVALID : OUT STD_LOGIC;
        m_axi_out_V_WREADY : IN STD_LOGIC;
        m_axi_out_V_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_out_V_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_V_WLAST : OUT STD_LOGIC;
        m_axi_out_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_ARVALID : OUT STD_LOGIC;
        m_axi_out_V_ARREADY : IN STD_LOGIC;
        m_axi_out_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_RVALID : IN STD_LOGIC;
        m_axi_out_V_RREADY : OUT STD_LOGIC;
        m_axi_out_V_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_out_V_RLAST : IN STD_LOGIC;
        m_axi_out_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_V_BVALID : IN STD_LOGIC;
        m_axi_out_V_BREADY : OUT STD_LOGIC;
        m_axi_out_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        out_V_offset : IN STD_LOGIC_VECTOR (57 downto 0);
        address : IN STD_LOGIC_VECTOR (63 downto 0);
        data_len : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dummy_compute IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        elemStream_V_V_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        elemStream_V_V_empty_n : IN STD_LOGIC;
        elemStream_V_V_read : OUT STD_LOGIC;
        data_len : IN STD_LOGIC_VECTOR (31 downto 0);
        resultStream_V_V_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        resultStream_V_V_full_n : IN STD_LOGIC;
        resultStream_V_V_write : OUT STD_LOGIC );
    end component;


    component fifo_w512_d512_A_x IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (511 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (511 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    grp_read_input_fu_126 : component read_input
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_read_input_fu_126_ap_start,
        ap_done => grp_read_input_fu_126_ap_done,
        ap_idle => grp_read_input_fu_126_ap_idle,
        ap_ready => grp_read_input_fu_126_ap_ready,
        m_axi_in_V_AWVALID => grp_read_input_fu_126_m_axi_in_V_AWVALID,
        m_axi_in_V_AWREADY => ap_const_logic_0,
        m_axi_in_V_AWADDR => grp_read_input_fu_126_m_axi_in_V_AWADDR,
        m_axi_in_V_AWID => grp_read_input_fu_126_m_axi_in_V_AWID,
        m_axi_in_V_AWLEN => grp_read_input_fu_126_m_axi_in_V_AWLEN,
        m_axi_in_V_AWSIZE => grp_read_input_fu_126_m_axi_in_V_AWSIZE,
        m_axi_in_V_AWBURST => grp_read_input_fu_126_m_axi_in_V_AWBURST,
        m_axi_in_V_AWLOCK => grp_read_input_fu_126_m_axi_in_V_AWLOCK,
        m_axi_in_V_AWCACHE => grp_read_input_fu_126_m_axi_in_V_AWCACHE,
        m_axi_in_V_AWPROT => grp_read_input_fu_126_m_axi_in_V_AWPROT,
        m_axi_in_V_AWQOS => grp_read_input_fu_126_m_axi_in_V_AWQOS,
        m_axi_in_V_AWREGION => grp_read_input_fu_126_m_axi_in_V_AWREGION,
        m_axi_in_V_AWUSER => grp_read_input_fu_126_m_axi_in_V_AWUSER,
        m_axi_in_V_WVALID => grp_read_input_fu_126_m_axi_in_V_WVALID,
        m_axi_in_V_WREADY => ap_const_logic_0,
        m_axi_in_V_WDATA => grp_read_input_fu_126_m_axi_in_V_WDATA,
        m_axi_in_V_WSTRB => grp_read_input_fu_126_m_axi_in_V_WSTRB,
        m_axi_in_V_WLAST => grp_read_input_fu_126_m_axi_in_V_WLAST,
        m_axi_in_V_WID => grp_read_input_fu_126_m_axi_in_V_WID,
        m_axi_in_V_WUSER => grp_read_input_fu_126_m_axi_in_V_WUSER,
        m_axi_in_V_ARVALID => grp_read_input_fu_126_m_axi_in_V_ARVALID,
        m_axi_in_V_ARREADY => m_axi_in_V_ARREADY,
        m_axi_in_V_ARADDR => grp_read_input_fu_126_m_axi_in_V_ARADDR,
        m_axi_in_V_ARID => grp_read_input_fu_126_m_axi_in_V_ARID,
        m_axi_in_V_ARLEN => grp_read_input_fu_126_m_axi_in_V_ARLEN,
        m_axi_in_V_ARSIZE => grp_read_input_fu_126_m_axi_in_V_ARSIZE,
        m_axi_in_V_ARBURST => grp_read_input_fu_126_m_axi_in_V_ARBURST,
        m_axi_in_V_ARLOCK => grp_read_input_fu_126_m_axi_in_V_ARLOCK,
        m_axi_in_V_ARCACHE => grp_read_input_fu_126_m_axi_in_V_ARCACHE,
        m_axi_in_V_ARPROT => grp_read_input_fu_126_m_axi_in_V_ARPROT,
        m_axi_in_V_ARQOS => grp_read_input_fu_126_m_axi_in_V_ARQOS,
        m_axi_in_V_ARREGION => grp_read_input_fu_126_m_axi_in_V_ARREGION,
        m_axi_in_V_ARUSER => grp_read_input_fu_126_m_axi_in_V_ARUSER,
        m_axi_in_V_RVALID => m_axi_in_V_RVALID,
        m_axi_in_V_RREADY => grp_read_input_fu_126_m_axi_in_V_RREADY,
        m_axi_in_V_RDATA => m_axi_in_V_RDATA,
        m_axi_in_V_RLAST => m_axi_in_V_RLAST,
        m_axi_in_V_RID => m_axi_in_V_RID,
        m_axi_in_V_RUSER => m_axi_in_V_RUSER,
        m_axi_in_V_RRESP => m_axi_in_V_RRESP,
        m_axi_in_V_BVALID => ap_const_logic_0,
        m_axi_in_V_BREADY => grp_read_input_fu_126_m_axi_in_V_BREADY,
        m_axi_in_V_BRESP => ap_const_lv2_0,
        m_axi_in_V_BID => ap_const_lv1_0,
        m_axi_in_V_BUSER => ap_const_lv1_0,
        in_V_offset => reg_189,
        address => reg_167,
        data_len => data_len,
        elemStream_V_V_din => grp_read_input_fu_126_elemStream_V_V_din,
        elemStream_V_V_full_n => elemStream_V_V_full_n,
        elemStream_V_V_write => grp_read_input_fu_126_elemStream_V_V_write);

    grp_write_output_fu_139 : component write_output
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_output_fu_139_ap_start,
        ap_done => grp_write_output_fu_139_ap_done,
        ap_idle => grp_write_output_fu_139_ap_idle,
        ap_ready => grp_write_output_fu_139_ap_ready,
        resultStream_V_V_dout => resultStream_V_V_dout,
        resultStream_V_V_empty_n => resultStream_V_V_empty_n,
        resultStream_V_V_read => grp_write_output_fu_139_resultStream_V_V_read,
        m_axi_out_V_AWVALID => grp_write_output_fu_139_m_axi_out_V_AWVALID,
        m_axi_out_V_AWREADY => m_axi_out_V_AWREADY,
        m_axi_out_V_AWADDR => grp_write_output_fu_139_m_axi_out_V_AWADDR,
        m_axi_out_V_AWID => grp_write_output_fu_139_m_axi_out_V_AWID,
        m_axi_out_V_AWLEN => grp_write_output_fu_139_m_axi_out_V_AWLEN,
        m_axi_out_V_AWSIZE => grp_write_output_fu_139_m_axi_out_V_AWSIZE,
        m_axi_out_V_AWBURST => grp_write_output_fu_139_m_axi_out_V_AWBURST,
        m_axi_out_V_AWLOCK => grp_write_output_fu_139_m_axi_out_V_AWLOCK,
        m_axi_out_V_AWCACHE => grp_write_output_fu_139_m_axi_out_V_AWCACHE,
        m_axi_out_V_AWPROT => grp_write_output_fu_139_m_axi_out_V_AWPROT,
        m_axi_out_V_AWQOS => grp_write_output_fu_139_m_axi_out_V_AWQOS,
        m_axi_out_V_AWREGION => grp_write_output_fu_139_m_axi_out_V_AWREGION,
        m_axi_out_V_AWUSER => grp_write_output_fu_139_m_axi_out_V_AWUSER,
        m_axi_out_V_WVALID => grp_write_output_fu_139_m_axi_out_V_WVALID,
        m_axi_out_V_WREADY => m_axi_out_V_WREADY,
        m_axi_out_V_WDATA => grp_write_output_fu_139_m_axi_out_V_WDATA,
        m_axi_out_V_WSTRB => grp_write_output_fu_139_m_axi_out_V_WSTRB,
        m_axi_out_V_WLAST => grp_write_output_fu_139_m_axi_out_V_WLAST,
        m_axi_out_V_WID => grp_write_output_fu_139_m_axi_out_V_WID,
        m_axi_out_V_WUSER => grp_write_output_fu_139_m_axi_out_V_WUSER,
        m_axi_out_V_ARVALID => grp_write_output_fu_139_m_axi_out_V_ARVALID,
        m_axi_out_V_ARREADY => ap_const_logic_0,
        m_axi_out_V_ARADDR => grp_write_output_fu_139_m_axi_out_V_ARADDR,
        m_axi_out_V_ARID => grp_write_output_fu_139_m_axi_out_V_ARID,
        m_axi_out_V_ARLEN => grp_write_output_fu_139_m_axi_out_V_ARLEN,
        m_axi_out_V_ARSIZE => grp_write_output_fu_139_m_axi_out_V_ARSIZE,
        m_axi_out_V_ARBURST => grp_write_output_fu_139_m_axi_out_V_ARBURST,
        m_axi_out_V_ARLOCK => grp_write_output_fu_139_m_axi_out_V_ARLOCK,
        m_axi_out_V_ARCACHE => grp_write_output_fu_139_m_axi_out_V_ARCACHE,
        m_axi_out_V_ARPROT => grp_write_output_fu_139_m_axi_out_V_ARPROT,
        m_axi_out_V_ARQOS => grp_write_output_fu_139_m_axi_out_V_ARQOS,
        m_axi_out_V_ARREGION => grp_write_output_fu_139_m_axi_out_V_ARREGION,
        m_axi_out_V_ARUSER => grp_write_output_fu_139_m_axi_out_V_ARUSER,
        m_axi_out_V_RVALID => ap_const_logic_0,
        m_axi_out_V_RREADY => grp_write_output_fu_139_m_axi_out_V_RREADY,
        m_axi_out_V_RDATA => ap_const_lv512_lc_1,
        m_axi_out_V_RLAST => ap_const_logic_0,
        m_axi_out_V_RID => ap_const_lv1_0,
        m_axi_out_V_RUSER => ap_const_lv1_0,
        m_axi_out_V_RRESP => ap_const_lv2_0,
        m_axi_out_V_BVALID => m_axi_out_V_BVALID,
        m_axi_out_V_BREADY => grp_write_output_fu_139_m_axi_out_V_BREADY,
        m_axi_out_V_BRESP => m_axi_out_V_BRESP,
        m_axi_out_V_BID => m_axi_out_V_BID,
        m_axi_out_V_BUSER => m_axi_out_V_BUSER,
        out_V_offset => reg_189,
        address => reg_167,
        data_len => data_len);

    grp_dummy_compute_fu_153 : component dummy_compute
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dummy_compute_fu_153_ap_start,
        ap_done => grp_dummy_compute_fu_153_ap_done,
        ap_idle => grp_dummy_compute_fu_153_ap_idle,
        ap_ready => grp_dummy_compute_fu_153_ap_ready,
        elemStream_V_V_dout => elemStream_V_V_dout,
        elemStream_V_V_empty_n => elemStream_V_V_empty_n,
        elemStream_V_V_read => grp_dummy_compute_fu_153_elemStream_V_V_read,
        data_len => data_len,
        resultStream_V_V_din => grp_dummy_compute_fu_153_resultStream_V_V_din,
        resultStream_V_V_full_n => resultStream_V_V_full_n,
        resultStream_V_V_write => grp_dummy_compute_fu_153_resultStream_V_V_write);

    elemStream_V_V_fifo_U : component fifo_w512_d512_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_read_input_fu_126_elemStream_V_V_din,
        if_full_n => elemStream_V_V_full_n,
        if_write => elemStream_V_V_write,
        if_dout => elemStream_V_V_dout,
        if_empty_n => elemStream_V_V_empty_n,
        if_read => elemStream_V_V_read);

    resultStream_V_V_fifo_U : component fifo_w512_d512_A_x
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_dummy_compute_fu_153_resultStream_V_V_din,
        if_full_n => resultStream_V_V_full_n,
        if_write => resultStream_V_V_write,
        if_dout => resultStream_V_V_dout,
        if_empty_n => resultStream_V_V_empty_n,
        if_read => resultStream_V_V_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dummy_compute_fu_153_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dummy_compute_fu_153_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dummy_compute_fu_153_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dummy_compute_fu_153_ap_ready = ap_const_logic_1)) then 
                    grp_dummy_compute_fu_153_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_read_input_fu_126_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_read_input_fu_126_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_read_input_fu_126_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_read_input_fu_126_ap_ready = ap_const_logic_1)) then 
                    grp_read_input_fu_126_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_write_output_fu_139_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_output_fu_139_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_write_output_fu_139_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_output_fu_139_ap_ready = ap_const_logic_1)) then 
                    grp_write_output_fu_139_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    reg_167_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                reg_167 <= mem_out_address;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                reg_167 <= mem_in_address;
            end if; 
        end if;
    end process;

    reg_189_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                reg_189 <= out_V_offset;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                reg_189 <= in_V_offset;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_read_input_fu_126_ap_done, grp_write_output_fu_139_ap_done, grp_dummy_compute_fu_153_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_read_input_fu_126_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_dummy_compute_fu_153_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_write_output_fu_139_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_write_output_fu_139_ap_done, ap_CS_fsm_state6)
    begin
        if ((((grp_write_output_fu_139_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_write_output_fu_139_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_write_output_fu_139_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    elemStream_V_V_read_assign_proc : process(grp_dummy_compute_fu_153_elemStream_V_V_read, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            elemStream_V_V_read <= grp_dummy_compute_fu_153_elemStream_V_V_read;
        else 
            elemStream_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    elemStream_V_V_write_assign_proc : process(grp_read_input_fu_126_elemStream_V_V_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            elemStream_V_V_write <= grp_read_input_fu_126_elemStream_V_V_write;
        else 
            elemStream_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_dummy_compute_fu_153_ap_start <= grp_dummy_compute_fu_153_ap_start_reg;
    grp_read_input_fu_126_ap_start <= grp_read_input_fu_126_ap_start_reg;
    grp_write_output_fu_139_ap_start <= grp_write_output_fu_139_ap_start_reg;
    m_axi_in_V_ARADDR <= grp_read_input_fu_126_m_axi_in_V_ARADDR;
    m_axi_in_V_ARBURST <= grp_read_input_fu_126_m_axi_in_V_ARBURST;
    m_axi_in_V_ARCACHE <= grp_read_input_fu_126_m_axi_in_V_ARCACHE;
    m_axi_in_V_ARID <= grp_read_input_fu_126_m_axi_in_V_ARID;
    m_axi_in_V_ARLEN <= grp_read_input_fu_126_m_axi_in_V_ARLEN;
    m_axi_in_V_ARLOCK <= grp_read_input_fu_126_m_axi_in_V_ARLOCK;
    m_axi_in_V_ARPROT <= grp_read_input_fu_126_m_axi_in_V_ARPROT;
    m_axi_in_V_ARQOS <= grp_read_input_fu_126_m_axi_in_V_ARQOS;
    m_axi_in_V_ARREGION <= grp_read_input_fu_126_m_axi_in_V_ARREGION;
    m_axi_in_V_ARSIZE <= grp_read_input_fu_126_m_axi_in_V_ARSIZE;
    m_axi_in_V_ARUSER <= grp_read_input_fu_126_m_axi_in_V_ARUSER;

    m_axi_in_V_ARVALID_assign_proc : process(ap_CS_fsm_state1, grp_read_input_fu_126_m_axi_in_V_ARVALID, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_in_V_ARVALID <= grp_read_input_fu_126_m_axi_in_V_ARVALID;
        else 
            m_axi_in_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_V_AWADDR <= ap_const_lv64_0;
    m_axi_in_V_AWBURST <= ap_const_lv2_0;
    m_axi_in_V_AWCACHE <= ap_const_lv4_0;
    m_axi_in_V_AWID <= ap_const_lv1_0;
    m_axi_in_V_AWLEN <= ap_const_lv32_0;
    m_axi_in_V_AWLOCK <= ap_const_lv2_0;
    m_axi_in_V_AWPROT <= ap_const_lv3_0;
    m_axi_in_V_AWQOS <= ap_const_lv4_0;
    m_axi_in_V_AWREGION <= ap_const_lv4_0;
    m_axi_in_V_AWSIZE <= ap_const_lv3_0;
    m_axi_in_V_AWUSER <= ap_const_lv1_0;
    m_axi_in_V_AWVALID <= ap_const_logic_0;
    m_axi_in_V_BREADY <= ap_const_logic_0;

    m_axi_in_V_RREADY_assign_proc : process(ap_CS_fsm_state1, grp_read_input_fu_126_m_axi_in_V_RREADY, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_in_V_RREADY <= grp_read_input_fu_126_m_axi_in_V_RREADY;
        else 
            m_axi_in_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_in_V_WDATA <= ap_const_lv512_lc_1;
    m_axi_in_V_WID <= ap_const_lv1_0;
    m_axi_in_V_WLAST <= ap_const_logic_0;
    m_axi_in_V_WSTRB <= ap_const_lv64_0;
    m_axi_in_V_WUSER <= ap_const_lv1_0;
    m_axi_in_V_WVALID <= ap_const_logic_0;
    m_axi_out_V_ARADDR <= ap_const_lv64_0;
    m_axi_out_V_ARBURST <= ap_const_lv2_0;
    m_axi_out_V_ARCACHE <= ap_const_lv4_0;
    m_axi_out_V_ARID <= ap_const_lv1_0;
    m_axi_out_V_ARLEN <= ap_const_lv32_0;
    m_axi_out_V_ARLOCK <= ap_const_lv2_0;
    m_axi_out_V_ARPROT <= ap_const_lv3_0;
    m_axi_out_V_ARQOS <= ap_const_lv4_0;
    m_axi_out_V_ARREGION <= ap_const_lv4_0;
    m_axi_out_V_ARSIZE <= ap_const_lv3_0;
    m_axi_out_V_ARUSER <= ap_const_lv1_0;
    m_axi_out_V_ARVALID <= ap_const_logic_0;
    m_axi_out_V_AWADDR <= grp_write_output_fu_139_m_axi_out_V_AWADDR;
    m_axi_out_V_AWBURST <= grp_write_output_fu_139_m_axi_out_V_AWBURST;
    m_axi_out_V_AWCACHE <= grp_write_output_fu_139_m_axi_out_V_AWCACHE;
    m_axi_out_V_AWID <= grp_write_output_fu_139_m_axi_out_V_AWID;
    m_axi_out_V_AWLEN <= grp_write_output_fu_139_m_axi_out_V_AWLEN;
    m_axi_out_V_AWLOCK <= grp_write_output_fu_139_m_axi_out_V_AWLOCK;
    m_axi_out_V_AWPROT <= grp_write_output_fu_139_m_axi_out_V_AWPROT;
    m_axi_out_V_AWQOS <= grp_write_output_fu_139_m_axi_out_V_AWQOS;
    m_axi_out_V_AWREGION <= grp_write_output_fu_139_m_axi_out_V_AWREGION;
    m_axi_out_V_AWSIZE <= grp_write_output_fu_139_m_axi_out_V_AWSIZE;
    m_axi_out_V_AWUSER <= grp_write_output_fu_139_m_axi_out_V_AWUSER;

    m_axi_out_V_AWVALID_assign_proc : process(ap_CS_fsm_state5, grp_write_output_fu_139_m_axi_out_V_AWVALID, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_out_V_AWVALID <= grp_write_output_fu_139_m_axi_out_V_AWVALID;
        else 
            m_axi_out_V_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_out_V_BREADY_assign_proc : process(ap_CS_fsm_state5, grp_write_output_fu_139_m_axi_out_V_BREADY, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_out_V_BREADY <= grp_write_output_fu_139_m_axi_out_V_BREADY;
        else 
            m_axi_out_V_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_out_V_RREADY <= ap_const_logic_0;
    m_axi_out_V_WDATA <= grp_write_output_fu_139_m_axi_out_V_WDATA;
    m_axi_out_V_WID <= grp_write_output_fu_139_m_axi_out_V_WID;
    m_axi_out_V_WLAST <= grp_write_output_fu_139_m_axi_out_V_WLAST;
    m_axi_out_V_WSTRB <= grp_write_output_fu_139_m_axi_out_V_WSTRB;
    m_axi_out_V_WUSER <= grp_write_output_fu_139_m_axi_out_V_WUSER;

    m_axi_out_V_WVALID_assign_proc : process(ap_CS_fsm_state5, grp_write_output_fu_139_m_axi_out_V_WVALID, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_out_V_WVALID <= grp_write_output_fu_139_m_axi_out_V_WVALID;
        else 
            m_axi_out_V_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    resultStream_V_V_read_assign_proc : process(grp_write_output_fu_139_resultStream_V_V_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            resultStream_V_V_read <= grp_write_output_fu_139_resultStream_V_V_read;
        else 
            resultStream_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    resultStream_V_V_write_assign_proc : process(grp_dummy_compute_fu_153_resultStream_V_V_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            resultStream_V_V_write <= grp_dummy_compute_fu_153_resultStream_V_V_write;
        else 
            resultStream_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
